### ISSUE TITLE
Infinite Music Play

### ISSUE THREAD

**Issue by NEWBIE0413** [jackthehack21/JukeBox-pmmp#11]
Infinite Music Play

Hi, I am a frequent user of your plug-in.
I'm going to tell you what I want to do to improve this plug-in.
The function I want is to play music infinitely.
It's too much of a hassle to change the record again when the song is finished. Please set the song to repeat in the config.
I am Korean and I am speaking using a translator. Please say the words in the comments that you don't understand.

**Comment by JaxkDev** [comment]
Plugin is being dropped, plan to merge to PM4.
