### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jennocool** [jackthehack21/JukeBox-pmmp#14]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]no

**Describe the solution you'd like**
If I use a resource pack and change the music wil the music be different

**Describe alternatives you've considered**

**Additional context**
Link of what I mean https://youtu.be/FWPiSKsseb0

**Comment by JaxkDev** [comment]
Plugin doesn’t touch the music, it’s all client sided I don’t know, most likely.
