### ISSUE TITLE
[BUG] 2 Bugs

### ISSUE THREAD

**Issue by Wertzui123** [jackthehack21/JukeBox-pmmp#6]
I hope this is a good issue:

I can't set the juke boxes, and when I set them via WorldEdit and klick on them with a vinyl record "Internal Server Error" and that is in the console:

[17:33:04] [Server thread/CRITICAL]: Error: "Call to a member function handleInteract() on null" (EXCEPTION) in "plugins/JukeBox-pmmp_dev-14.phar/src/Jackthehack21/JukeBox/Block/JukeBox" at line 59

PmmP Version: 3.6.4
OS: Linux
Plugin Version: Version 1.0.0

**Comment by JaxkDev** [comment]
Setting blocks by plugins may not work it will only work if you place it.

And that’s still not the format, it gives you a template follow it.

**Comment by JaxkDev** [comment]
Please reply with the full issue format about not being able to set them from creative inventory.
Plugins setting blocks will most likely fail.

**Comment by SyntaxDragon** [comment]
I can confirm that you have to manually place JukeBoxes yourself

I can try and replicating his issue
